### ISSUE TITLE
Error massages

### ISSUE THREAD

**Issue by Sammino** [jeffcrouse/CodeForArt#1]
Hi 
I am an absolute beginner trying to figure out what these all mean. When I copy the code and past in the testApp.cpp, I get the error message that displays in the image below. Any help will be greatly appreciated
Cheers
Sam

![errorMessage](https://f.cloud.github.com/assets/3503775/138181/20728124-7190-11e2-8453-2374ddcabc80.png)

**Comment by jeffcrouse** [comment]
Hey Sammino -- make sure you copy+paste the code in testApp.h also!

**Comment by Sammino** [comment]
Thanks mate
